### ISSUE TITLE
Auto Affinity Converter question

### ISSUE THREAD

**Issue by steida** [mphill/kysely-expo#2]
Hi, if I'm reading the source code correctly, Auto Affinity Converter doesn't handle the case someone stores a "true" into a string column, which will be automatically converted into a boolean despite the fact it's a string.

**Comment by mphill** [comment]
That’s correct, from their docs. 

> 2.1. Boolean Datatype
> 
> SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
> 
> SQLite recognizes the keywords "TRUE" and "FALSE", as of version 3.23.0 (2018-04-02) but those keywords are just alternative spellings for the integer literals 1 and 0 respectively.


When I was working through this storing as strings would seem safer to use, but it’s not bulletproof.  It’s much more common to see 0 or 1 outside of booleans. If that makes sense. 

If you have any ideas on a better way I’d appreciate any feedback.

**Comment by steida** [comment]
No, I have not. I tried to solve it for https://github.com/evoluhq/evolu somehow, and it's not possible. Evolu automatically parses JSON strings into objects, and for that case, Evolu string columns must be implemented via Schema, ensuring people will not store JSON strings in a string column. Anything else is not possible.

**Comment by mphill** [comment]
If you look at this issue: https://github.com/mphill/kysely-expo/issues/1

The original design used naming conventions.

For instance, if a property met the following criteria:

` "is_*" `or `"*_flag"` it would be treated as a `boolean`

likewise something `"*_at"` would be converted to a `Date`

That was the only other option I had explored, clearly **not** super,  but it's pretty bulletproof.

Using strings to store `booleans` seems like the best compromise, calling `.toString() `on `true` or `false` will result in `"true"` and `"false"`.

**Comment by steida** [comment]
Naming convention seems to be a good idea and trade-off, why it's "original design"?

**Comment by mphill** [comment]
This is how it works as an example:

![image](https://github.com/mphill/kysely-expo/assets/2466039/bc20be38-f47a-42b6-a5b4-da0adbeaada3)

I added it back and updated the README.  This library can do both now.
