### ISSUE TITLE
Support Expo 52

### ISSUE THREAD

**Issue by dguenther** [mphill/kysely-expo#3]
I believe the main changes needed here are to upgrade the `expo-sqlite` dependency to 15, and to change uses of `expo-sqlite/next` to `expo-sqlite`.

I made these changes in my node_modules and it seemed to work, however I saw a bunch of these errors in the logs, which might mean there's more to do:

```
[libsqlite3.dylib] API call with unopened database connection pointer
[libsqlite3.dylib] misuse at line 142281 of [1b37c146ee]
```

**Comment by mphill** [comment]
@dguenther Can you try version 3.0.0, you should be set.
