### ISSUE TITLE
Mocking KyselyProvider

### ISSUE THREAD

**Issue by philscott-dev** [mphill/kysely-expo#4]
"expo": "~52.0.17",
 "kysely": "^0.27.5",
 "kysely-expo": "^3.0.0",
 "jest": "^29.7.0",
 "jest-expo": "~52.0.2",

👋 Hello! I'm running into a little issue where if try mock KyselyProvider in `jest.setup.js` KyselyProvider is undefined, but if mocked directly in my test file this is no longer the case:

```
jest.mock('kysely-expo', () => ({
  KyselyProvider: jest.fn(),
}))
```

I'm using the vanilla jest-expo preset, and have tried with and without adding kysely-expo to `transformIgnorePatterns`. This very well may be an issue with jest or my project, but figured I'd start here and see. Thanks!

**Comment by mphill** [comment]
I'm afraid I won't be much help solving your testing use case.

But I will say using TS for your mocks would allow you to use utility types like:

https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype
https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype

That would allow you to do something like this:

```ts
type MyFunctionReturnType = ReturnType<typeof myFunction>;

const mockMyFunction = jest.fn<MyFunctionReturnType, Parameters<typeof myFunction>>()
  .mockReturnValue(100); // Return a specific value
```
